### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by tongrendx** [SonicCloudOrg/sonic-ios-bridge#22]
Class LRUCache is implemented in both /System/Library/Frameworks/CFNetwork.framework/CFNetwork (0x201797e60) and /private/var/containers/Bundle/Application/B17778EB-F857-4604-9B18-091D7AB1750A/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib (0x106f5daf0). One of the two will be used. Which one is undefined.

**Comment by ZhouYixun** [comment]
> Class LRUCache is implemented in both /System/Library/Frameworks/CFNetwork.framework/CFNetwork (0x201797e60) and /private/var/containers/Bundle/Application/B17778EB-F857-4604-9B18-091D7AB1750A/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib (0x106f5daf0). One of the two will be used. Which one is undefined.

复现步骤是什么，报错又是哪里出现的?

**Comment by ZhouYixun** [comment]
https://sonic-cloud.wiki/ 去这边提问吧，这边我回复快一点
