### ISSUE TITLE
查看文件提示 afc 'Open': UnknownError 

### ISSUE THREAD

**Issue by Linxi-brave** [SonicCloudOrg/sonic-ios-bridge#30]
可以连上设备
wdkj@wdkjdeMacBook-Pro sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib devices   
00008101-000A2C561100001E online

想要查看设备文件，提示 afc 'Open': UnknownError ，不知道如何查看
wdkj@wdkjdeMacBook-Pro sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib afc cat -f .
afc 'Open': UnknownError
<img width="569" alt="image" src="https://user-images.githubusercontent.com/19731510/185551688-cf15fb46-a16d-44a1-8c7c-744aba53b45a.png">

**Comment by ZhouYixun** [comment]
> 可以连上设备 wdkj@wdkjdeMacBook-Pro sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib devices 00008101-000A2C561100001E online
> 
> 想要查看设备文件，提示 afc 'Open': UnknownError ，不知道如何查看 wdkj@wdkjdeMacBook-Pro sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib afc cat -f . afc 'Open': UnknownError <img alt="image" width="569" src="https://user-images.githubusercontent.com/19731510/185551688-cf15fb46-a16d-44a1-8c7c-744aba53b45a.png">

你好，可以先试用1.1.8版本

先执行`sib mount`
然后执行`./sib afc cat -f /DCIM/`试试看

**Comment by Linxi-brave** [comment]
你好，邮件已收到，将尽快处理并回复。

**Comment by Linxi-brave** [comment]
你好，我执行过挂载了，还是报一样的错误。


还有，就是作为测试，有时候想看开发存储在App本地数据，看看有没有敏感信息或者加密，这个工具可以看么。





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Eason ***@***.***&gt;
发送时间: 2022年8月19日 15:54
收件人: SonicCloudOrg/sonic-ios-bridge ***@***.***&gt;
抄送: Linxi-brave ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)

**Comment by ZhouYixun** [comment]
> 你好，我执行过挂载了，还是报一样的错误。 还有，就是作为测试，有时候想看开发存储在App本地数据，看看有没有敏感信息或者加密，这个工具可以看么。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Eason ***@***.***&gt; 发送时间: 2022年8月19日 15:54 收件人: SonicCloudOrg/sonic-ios-bridge ***@***.***&gt; 抄送: Linxi-brave ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30)

部分app是可以看到本地文件的，不知道是不是你说的需求。

这个报错的话让 @aoliaoaoaojiao  小伙伴看看

**Comment by ZhouYixun** [comment]
可以提供更详细的报错log和ios版本信息吗

**Comment by aoliaoaoaojiao** [comment]
> 可以连上设备 wdkj@wdkjdeMacBook-Pro sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib devices 00008101-000A2C561100001E online
> 
> 想要查看设备文件，提示 afc 'Open': UnknownError ，不知道如何查看 wdkj@wdkjdeMacBook-Pro sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib afc cat -f . afc 'Open': UnknownError <img alt="image" width="569" src="https://user-images.githubusercontent.com/19731510/185551688-cf15fb46-a16d-44a1-8c7c-744aba53b45a.png">

你好，能提供下iOS版本和硬件设备信息吗？如果是比较老的iOS版本的话，其实并没有提供afc服务支持，其操作文件使用的通讯服务是另外一个

**Comment by Linxi-brave** [comment]
ios 版本信息为：iPhone 12 mini 15.0.2
报错log 就只有一句话 ：&nbsp;afc 'Open': UnknownError&nbsp;


问了开发人员说APP存储数据是在APP沙盒中的，系统级别不允许被内部访问的 。
其实我这边主要是想看APP存储数据是否有加密、是否有敏感信息 这样子 。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-ios-bridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)





 
可以提供更详细的报错log和ios版本信息吗

**Comment by Linxi-brave** [comment]
应该不是没有提供afc服务，因为我执行&nbsp;./sib afc pull -d . -l ./log&nbsp;将文件导出到本地电脑，是可以成功的 。




***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib afc cat -f .

afc 'Open': UnknownError

***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 %&nbsp;

***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib afc pull -d . -l ./log





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-ios-bridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)





  
可以连上设备 ***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib devices 00008101-000A2C561100001E online
 
想要查看设备文件，提示 afc 'Open': UnknownError ，不知道如何查看 ***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib afc cat -f . afc 'Open': UnknownError 
  
你好，能提供下iOS版本和硬件设备信息吗？如果是比较老的iOS版本的话，其实并没有提供afc服务支持，其操作文件使用的通讯服务是另外一个

**Comment by aoliaoaoaojiao** [comment]
执行的命令好像有点问题，afc cat 是只能看文件的，你输入的是 "."，gidevice读取文件"."失败，返回的报错

**Comment by aoliaoaoaojiao** [comment]
> 应该不是没有提供afc服务，因为我执行&nbsp;./sib afc pull -d . -l ./log&nbsp;将文件导出到本地电脑，是可以成功的 。 ***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib afc cat -f . afc 'Open': UnknownError ***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 %&nbsp; ***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib afc pull -d . -l ./log
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SonicCloudOrg/sonic-ios-bridge" ***@***.***&gt;; 发送时间:&nbsp;2022年8月19日(星期五) 下午4:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30) 可以连上设备 ***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib devices 00008101-000A2C561100001E online 想要查看设备文件，提示 afc 'Open': UnknownError ，不知道如何查看 ***@***.*** sonic-ios-bridge_1.1.7_macosx_x86_64 % ./sib afc cat -f . afc 'Open': UnknownError 你好，能提供下iOS版本和硬件设备信息吗？如果是比较老的iOS版本的话，其实并没有提供afc服务支持，其操作文件使用的通讯服务是另外一个 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

 ./sib afc cat -f .这个命令是错的，cat不支持文件夹，需要查看文件夹信息请使用tree或者ls命令

**Comment by Linxi-brave** [comment]
还有请问一下，这个工具可以看 某个APP的存储数据吗&nbsp; ，就是存储在iOS系统沙盒里面的数据 ，那个好像才是应用程序文件夹&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "梦幻雨虹"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午5:08
***@***.***&gt;;

主题:&nbsp;回复： [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)



好了，我试了指定文件，并没有报错；
建议把报错信息修改一下哦 ，因为现在是unknown，真的看不出来 ，







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-ios-bridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)





 
执行的命令好像有点问题，afc cat 是只能看文件的，你输入的是 "."，gidevice读取文件"."失败，返回的报错

**Comment by aoliaoaoaojiao** [comment]
> 还有请问一下，这个工具可以看 某个APP的存储数据吗&nbsp; ，就是存储在iOS系统沙盒里面的数据 ，那个好像才是应用程序文件夹&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "梦幻雨虹" ***@***.***&gt;; 发送时间:&nbsp;2022年8月19日(星期五) 下午5:08 ***@***.***&gt;; 主题:&nbsp;回复： [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30) 好了，我试了指定文件，并没有报错； 建议把报错信息修改一下哦 ，因为现在是unknown，真的看不出来 ，
> ------------------ 原始邮件 ------------------ 发件人: "SonicCloudOrg/sonic-ios-bridge" ***@***.***&gt;; 发送时间:&nbsp;2022年8月19日(星期五) 下午5:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30) 执行的命令好像有点问题，afc cat 是只能看文件的，你输入的是 "."，gidevice读取文件"."失败，返回的报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

只要开发开放了对应的权限就能访问，例如沙盒里的document文件：afc  ls /Documents/  -b com.apple.clips

**Comment by aoliaoaoaojiao** [comment]
> 还有请问一下，这个工具可以看 某个APP的存储数据吗&nbsp; ，就是存储在iOS系统沙盒里面的数据 ，那个好像才是应用程序文件夹&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "梦幻雨虹" ***@***.***&gt;; 发送时间:&nbsp;2022年8月19日(星期五) 下午5:08 ***@***.***&gt;; 主题:&nbsp;回复： [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30) 好了，我试了指定文件，并没有报错； 建议把报错信息修改一下哦 ，因为现在是unknown，真的看不出来 ，
> ------------------ 原始邮件 ------------------ 发件人: "SonicCloudOrg/sonic-ios-bridge" ***@***.***&gt;; 发送时间:&nbsp;2022年8月19日(星期五) 下午5:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30) 执行的命令好像有点问题，afc cat 是只能看文件的，你输入的是 "."，gidevice读取文件"."失败，返回的报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问下问题是否解决？

**Comment by Linxi-brave** [comment]
问了一下ios开发，他说 ，开发没有开放目录使用权限的能力. 这是系统控制的.&nbsp; &nbsp;这个是原话。
我现在也不知道谁说的是对的了。我也不懂这个 。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-ios-bridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)





  
还有请问一下，这个工具可以看 某个APP的存储数据吗&nbsp; ，就是存储在iOS系统沙盒里面的数据 ，那个好像才是应用程序文件夹&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "梦幻雨虹" @.&gt;; 发送时间:&nbsp;2022年8月19日(星期五) 下午5:08 @.&gt;; 主题:&nbsp;回复： [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30) 好了，我试了指定文件，并没有报错； 建议把报错信息修改一下哦 ，因为现在是unknown，真的看不出来 ，
 ------------------ 原始邮件 ------------------ 发件人: "SonicCloudOrg/sonic-ios-bridge" @.&gt;; 发送时间:&nbsp;2022年8月19日(星期五) 下午5:01 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30) 执行的命令好像有点问题，afc cat 是只能看文件的，你输入的是 "."，gidevice读取文件"."失败，返回的报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
请问下问题是否解决？

**Comment by Linxi-brave** [comment]
他还说了这些




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "梦幻雨虹"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午5:23
***@***.***&gt;;

主题:&nbsp;回复： [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)



问了一下ios开发，他说 ，开发没有开放目录使用权限的能力. 这是系统控制的.&nbsp; &nbsp;这个是原话。
我现在也不知道谁说的是对的了。我也不懂这个 。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-ios-bridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)





  
还有请问一下，这个工具可以看 某个APP的存储数据吗&nbsp; ，就是存储在iOS系统沙盒里面的数据 ，那个好像才是应用程序文件夹 
 …
 ------------------ 原始邮件 ------------------ 发件人: "梦幻雨虹" @.&gt;; 发送时间: 2022年8月19日(星期五) 下午5:08 @.&gt;; 主题: 回复： [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30) 好了，我试了指定文件，并没有报错； 建议把报错信息修改一下哦 ，因为现在是unknown，真的看不出来 ，
 ------------------ 原始邮件 ------------------ 发件人: "SonicCloudOrg/sonic-ios-bridge" @.&gt;; 发送时间: 2022年8月19日(星期五) 下午5:01 @.&gt;; @.@.&gt;; 主题: Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError (Issue #30) 执行的命令好像有点问题，afc cat 是只能看文件的，你输入的是 "."，gidevice读取文件"."失败，返回的报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
请问下问题是否解决？

**Comment by aoliaoaoaojiao** [comment]
> 他还说了这些

以你们开发说法为主

**Comment by Linxi-brave** [comment]
但是他说 ，
如果打个允许开放权限的包，用户端确定使用权限，就可以访问这些文件。
这个情况可以用&nbsp;sonic-ios-bridge 这个工具查看到这些文件吗 ？&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-ios-bridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)





  
他还说了这些
  
以你们开发说法为主

**Comment by aoliaoaoaojiao** [comment]
> 但是他说 ， 如果打个允许开放权限的包，用户端确定使用权限，就可以访问这些文件。 这个情况可以用&nbsp;sonic-ios-bridge 这个工具查看到这些文件吗 ？&nbsp;

AFC是iOS用来进行文件操作的相关通信协议，而应用沙盒内的文件是否可以访问，取决于系统对这些文件/文件夹的权限是否开发，如果开发可以将其他文件夹及其里面的文件的权限提升至和com.apple.clips的Documents一样，则可以访问。相关问题你可以到sonic社区讨论，目前你需要讨论的内容已经超过这个lssues的主题范围了，而你最初的问题目前还没有反馈是否解决，我们可以合理的推测已经解决了，不久将会关闭这个lssues

**Comment by aoliaoaoaojiao** [comment]
> 但是他说 ， 如果打个允许开放权限的包，用户端确定使用权限，就可以访问这些文件。 这个情况可以用&nbsp;sonic-ios-bridge 这个工具查看到这些文件吗 ？&nbsp;

AFC是iOS用来进行文件操作的相关通信协议，而应用沙盒内的文件是否可以访问，取决于系统对这些文件/文件夹的权限是否开放，如果开发可以将其他文件夹及其里面的文件的权限提升至和com.apple.clips的Documents一样，则可以访问。相关问题你可以到sonic社区讨论，目前你需要讨论的内容已经超过这个lssues的主题范围了，而你最初的问题目前还没有反馈是否解决，我们可以合理的推测已经解决了，不久将会关闭这个lssues

**Comment by ZhouYixun** [comment]
如果没问题了，我们暂时先关闭issue

**Comment by Linxi-brave** [comment]
好呢，没有问题呢，谢谢了&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-ios-bridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)





 
如果没问题了，我们暂时先关闭issue

**Comment by Linxi-brave** [comment]
你好，邮件已收到，将尽快处理并回复。

**Comment by Linxi-brave** [comment]
好了，我试了指定文件，并没有报错；
建议把报错信息修改一下哦 ，因为现在是unknown，真的看不出来 ，







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-ios-bridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-ios-bridge] 查看文件提示 afc 'Open': UnknownError  (Issue #30)





 
执行的命令好像有点问题，afc cat 是只能看文件的，你输入的是 "."，gidevice读取文件"."失败，返回的报错
