### ISSUE TITLE
【Bug】Get no output with afc ls

### ISSUE THREAD

**Issue by Hcu** [SonicCloudOrg/sonic-ios-bridge#47]
**在提出此issue时，我确认了以下几点（保存后请点击复选框）：**

**Bug 描述**

Hi, I'm trying to see the contents of the directory of the WebDriverAgentRunner application that I have installed on my device.
I'm using the following command on my Mac machine with a single device attached:

```
% ./sib afc ls -b com.facebook.WebDriverAgentRunner.xctrunner -f /
```

I get no output.

When I run the same command with [ios-deploy](https://github.com/ios-control/ios-deploy)

```
% ios-deploy --bundle_id com.facebook.WebDriverAgentRunner.xctrunner -l /
[....] Waiting for iOS device to be connected
[....] Using xxxxxxxxxxxxxxxxxxxx (J127AP, iPad Pro (9.7"), iphoneos, arm64, 15.7, 19H12) a.k.a. 'iPad'.
//
/Documents/
/Library/
/Library/Caches/
/Library/Caches/com.apple.dyld/
/Library/Caches/com.apple.dyld/WebDriverAgentRunner-Runner.dyld4
/Library/Caches/com.facebook.WebDriverAgentRunner.xctrunner/
/Library/Caches/com.facebook.WebDriverAgentRunner.xctrunner/com.apple.metalfe/
/Library/Preferences/
/Library/Preferences/com.facebook.WebDriverAgentRunner.xctrunner.plist
/Library/Saved Application State/
/Library/Saved Application State/com.facebook.WebDriverAgentRunner.xctrunner.savedState/
/Library/Saved Application State/com.facebook.WebDriverAgentRunner.xctrunner.savedState/KnownSceneSessions/
/Library/Saved Application State/com.facebook.WebDriverAgentRunner.xctrunner.savedState/KnownSceneSessions/data.data
/Library/SplashBoard/
/tmp/
/tmp/05d18014-d6f8-4ce8-ba83-2da3ca76bed8.xctestconfiguration
/tmp/1a27dc90-df5e-4481-8603-edadee09fbd2.xctestconfiguration
/tmp/1ef97934-8c95-41d6-9964-ca86ad42ea0a.xctestconfiguration
/tmp/4118db3b-245a-42f6-a4d7-213eeb6a1198.xctestconfiguration

```

I've tried with other bundleid's of applications on the device and get the same results, ios-deploy will output the contents, but sonic will return no results.

**版本**
Sonic的版本号 | Sonic's Version.

Tested on a Mac OS, with Sonic version 1.2.7

**Comment by ZhouYixun** [comment]
Thanks for your feedback, we will try to repair it in the near future

**Comment by ZhouYixun** [comment]
The implementation mechanisms of the two are different. iOS deploy integrates official lib directly, while we hack the official DTX protocol, so the effect is worse than that of official support
