### ISSUE TITLE
sib 怎么实现ssh ios连接  端口怎么实现转发  ？

### ISSUE THREAD

**Issue by eachlove** [SonicCloudOrg/sonic-ios-bridge#54]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

我只想使用sib远程连接手机 

### Deploy platform

Macos

### Minimal reproduce step

默认就是9123了  不是应该把22 映射到9123了 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
https://sonic-cloud.cn/sib/sib-remote.html 文档在这里哦，也可以使用-p 指定端口
