### ISSUE TITLE
[Q]  An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by luoxiao1008** [SonicCloudOrg/sonic-ios-bridge#56]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

null

### Deploy platform

null

### Minimal reproduce step

执行过程中突然就会报这种错，代表啥意思  
  t =  3979.46s Get all elements bound by accessibility element for: Elements matching predicate 'BLOCKPREDICATE(0x280219f50)'
    t =  3979.47s     Requesting snapshot of accessibility hierarchy for app with pid 6728
    t =  3979.58s     Find: Descendants matching type Any
    t =  3979.58s     Find: Elements matching predicate 'BLOCKPREDICATE(0x280219f50)'
2023/03/14 20:38:07 local <- remote failed: readfrom tcp 127.0.0.1:64243->127.0.0.1:27015: write tcp 127.0.0.1:64243->127.0.0.1:27015: wsasend: An established connection was aborted by the software in your host machine.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你本地开了代理吗

**Comment by luoxiao1008** [comment]
本地并没有，就启动了这个sib run wda -b com.facebook.WebDriverAgentRunner.xctrunner

**Comment by ZhouYixun** [comment]
感觉是wda断连了，你确认下你的代码是不是设置了wda不响应会断开的设置，是appium吗

**Comment by luoxiao1008** [comment]
不是用的appium，用的facebook-wda目前就配置了这个{'waitForIdleTimeout': 1}

**Comment by ZhouYixun** [comment]
> 不是用的appium，用的facebook-wda目前就配置了这个{'waitForIdleTimeout': 1}

看下你所有配置

**Comment by ZhouYixun** [comment]
不过我用的appium-wda测试的，facebook的貌似有问题

**Comment by luoxiao1008** [comment]
> > 不是用的appium，用的facebook-wda目前就配置了这个{'waitForIdleTimeout': 1}
> 
> 看下你所有配置
{'boundElementsByIndex': False, 'mjpegServerFramerate': 10, 'screenshotOrientation': 'auto', 'reduceMotion': False, 'elementResponseAttributes': 'type,label', 'screenshotQuality': 1, 'mjpegScalingFactor': 100, 'keyboardPrediction': 0, 'defaultActiveApplication': 'auto', 'mjpegServerScreenshotQuality': 25, 'defaultAlertAction': '', 'keyboardAutocorrection': 0, 'useFirstMatch': False, 'shouldUseCompactResponses': True, 'customSnapshotTimeout': 15, 'dismissAlertButtonSelector': '', 'activeAppDetectionPoint': '64.00,64.00', 'snapshotMaxDepth': 50, 'waitForIdleTimeout': 10, 'includeNonModalElements': False, 'acceptAlertButtonSelector': '', 'animationCoolOffTimeout': 2}
这种配置吗？
另外我试的一台电脑是是可以不会报错的，另外一台一定会报错，啥配置会影响呢

**Comment by ZhouYixun** [comment]
那感觉是电脑问题，是不是有东西冲突了

**Comment by luoxiao1008** [comment]
又有好几台pc也这样，还是没搞定，这个到底是啥冲突了，试了也不是8100端口使用冲突了

**Comment by ZhouYixun** [comment]
> 又有好几台pc也这样，还是没搞定，这个到底是啥冲突了，试了也不是8100端口使用冲突了

重启设备和电脑也不行吗

**Comment by luoxiao1008** [comment]
我知道了，执行了d = wda.Client('http://localhost:8100')连接之后，我这边会去做其他设备配置，然后如果超过2min，再回来继续执行自动化，就一定会出现这个报错，应该是啥连接超时了
