### ISSUE TITLE
[Q] I run webdriveragent to automate UI testing and measure performance(sib perfmon command) at the same time, will webdriveragent crash or behave abnormally? 

### ISSUE THREAD

**Issue by myungkyojung** [SonicCloudOrg/sonic-ios-bridge#60]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v1.3.12

### Deploy platform

macOS 11.6.5

### Minimal reproduce step

I run webdriveragent to automate UI testing and measure performance(sib perfmon command) at the same time.
I have an issue with webdriveragent not responding to requests.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
Our device testing did not encounter this issue

**Comment by ZhouYixun** [comment]
We tested again this weekend and there were no issues. I think most machines support webdriversagent and sib perfmon running simultaneously

**Comment by myungkyojung** [comment]
@ZhouYixun 
Thank you for your feedback.
I did some additional testing.
The issue seems to be caused by a memory leak issue in Webdriveragent (find element request).
