### ISSUE TITLE
[question][allows your to control ios device on browser ]

### ISSUE THREAD

**Issue by carloslopera89** [SonicCloudOrg/sonic-ios-bridge#62]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

In this moment i used the version 1.3.14, this solution es wonderfull and work very good for me , i have a question ,
when a execute in my terminal the command `sib run wda -b com.facebook.WebDriverAgentRunner.xctrunner --mjpeg-local-port=8101 --mjpeg-remote-port=8200 -u c837fb22ec60eb8f3de743897879131948796eed`
in the browser the mirror its perfect 
<img width="1240" alt="Captura de pantalla 2023-07-28 a la(s) 11 18 48 p m" src="https://github.com/SonicCloudOrg/sonic-ios-bridge/assets/8334608/76794576-47c9-4be5-905e-f906b79131eb">
 but is only mirror
¿ its possible the implementation take a control remote for de device ios?

### Deploy platform

Mac book Pro (Intel)
mac OS Ventura 13.3.1

### Minimal reproduce step

No its a bug , is more a question

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
You can try using our complete platform. This plugin can only achieve screen projection. If you want to achieve touch function, you can initiate an HTTP interface for WDA yourself

**Comment by clopera89** [comment]
Thank you very much, could you please tell me how I can start an HTTP interface for WDA or how I can see information about the complete solution that it indicates. I am very grateful for your help

**Comment by ZhouYixun** [comment]
No problem. What programming language are you familiar with？

**Comment by ZhouYixun** [comment]
You can check out our other project https://github.com/SonicCloudOrg/sonic-driver-core, which is very easy to use java to manipulate wda, you can find examples in the test class

**Comment by clopera89** [comment]
Thank you @ZhouYixun , this implementation works perfectly for me, I have a question about the manipulation of WDA, it is only possible to do it from automation, for example if I want to manipulate the device manually only from the browser it is possible to do it

**Comment by ZhouYixun** [comment]
This is certainly possible, and we do it with sonic's complete platform, where you can go to the website and deploy our server and agent to experience full ios control, which is free and open source. If you want to just go through sib and wda, then maybe you also need a web page development

**Comment by clopera89** [comment]
@ZhouYixun , perfect, could you tell me how to access this implementation  with sonic's complete platform, or some reference example for this?

And thanks again for your help

**Comment by ZhouYixun** [comment]
https://sonic-cloud.cn/en/deploy/back-end-deploy.html

Our official website has complete deployment steps
