### ISSUE TITLE
[Bug] sib encounters errors, the rest of the devices become OFFLINE

### ISSUE THREAD

**Issue by sam80180** [SonicCloudOrg/sonic-ios-bridge#63]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sonic-ios-bridge 1.3.13

### Deploy platform

Linux

### Minimal reproduce step

When running 'listen' or 'device list with detail' commands and sonic-ios-bridge encounters errors, e.g. 'PairingDialogResponsePending', it stops retrieving information of the rest of the devices, which in turn causes those devices appear to be OFFLINE on the Sonic portal.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
fix in #64
