### ISSUE TITLE
Error: failed send the command [launch], you can use [sib mount] command to fix it and retry, err : Request to launch com.facebook.WebDriverAgentRunner.xcrunner failed.

### ISSUE THREAD

**Issue by kingson09** [SonicCloudOrg/sonic-ios-bridge#65]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v1.3.15，启动wda报错Error: failed send the command [launch], you can use [sib mount] command to fix it and retry, err : Request to launch com.facebook.WebDriverAgentRunner.xcrunner failed.
sib install可以正常运行

### Deploy platform

linux x86 ,mac x86都不行

### Minimal reproduce step

按照教程

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你点一下这个应用，会出现什么？
