### ISSUE TITLE
[Enhancement] Multiple host support for Remote command 

### ISSUE THREAD

**Issue by Himanshu-Gurjar** [SonicCloudOrg/sonic-ios-bridge#71]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

1.3.16

### Deploy platform

Ubuntu 20.04

### Minimal reproduce step

N/A

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
what?

**Comment by Himanshu-Gurjar** [comment]
As of now Remote command support only single host

something like `sib remote connect --host 192.168.1.1`

Here we can provide only single host so the devices which are connected over that host gets connected locally,
so, it is possible that we can provide multiple different hosts and all the devices connected to those different hosts are available locally. 

something like this is possible?

**Comment by ZhouYixun** [comment]
A device can be `sib remote share` and then `sib remote connect` on multiple different computers.

share from local host like 192.168.1.1

other computer -> connect 192.168.1.1

**Comment by ZhouYixun** [comment]
> It does not support any other port apart from 9123? And my question was different,
> 
> So for example I've a server and 3 mac systems I've connected 2 device in mac1 2 device in mac2 and 2 device in mac3 and exposed the usbmuxd socket connection over different port on server so 4444 for mac1 5555 for mac2 and 6666 for mac3 on server this are accessible on respective port
> 
> It is possible that I can provide this 3 different connection in the --host argument and connect all those 6 device in server itself?

you should use -p to setting port

**Comment by ZhouYixun** [comment]
Why not give it a try? `sib remote` just connect with http, not for usbmuxd
