### ISSUE TITLE
同一个WDA工程，在XCode14.3上跑出来的WDA，Sib run wda正常，在Xcode15.0.1上跑出来的WDA，Sib run wda失败

### ISSUE THREAD

**Issue by guoxiangyang163** [SonicCloudOrg/sonic-ios-bridge#72]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sonic 1.3.13
sib  1.3.17

### Deploy platform

sib  1.3.17
Xcode 14.3
Xcode 15.01

### Minimal reproduce step

同一个WDA工程，在XCode14.3上跑出来的WDA，Sib run wda正常，升级MACOS系统14.1.1后已不支持XCode14，在Xcode15.0.1上跑出来的WDA，Sib run wda失败，指令和反馈如下，没有返回error原因，我不确定XCode15跑出来的WDA和XCode14有什么不同，WDA工程代码和配置都没有更改，两个版本跑出来的WDA 都是可以通过手动点击启动的，但结果是使用Sib则一个成功，一个失败

(base) xiangyang.guo@guosMBP sonic-ios-bridge_1.3.17_macosx_arm64 % ./sib run wda -b com.mtp.WebDriverAgentRunner.yk
2023-12-21 15:20:33.813069+0800 WebDriverAgentRunner-Runner[5115:870438] [Default] Running tests...
2023-12-21 15:20:33.916663+0800 WebDriverAgentRunner-Runner[5115:870438] [Default] Error while preparing for testing: (null)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
暂时需要更换xcode版本来适配不同的iOS版本

**Comment by guoxiangyang163** [comment]
这个意思是说，目前对于iOS16及以下系统，还不能用XCode15来构建是吧
另外还有个问题不知是否能解答，我用XCode14打WDA ipa包之后，发现首次安装到真机会出现Sib启动不了WDA的情况，log如下
2023-12-28 18:01:30.453  INFO 68097 --- [      Thread-10] com.msxf.mtp.agent.bridge.ios.SibTool    : WebDriverAgent server start failed: receive packet: InvalidService
2023-12-28 18:01:30.453  INFO 68097 --- [      Thread-10] com.msxf.mtp.agent.bridge.ios.SibTool    : WebDriverAgent print thread shutdown.

但是真机一旦用XCode成功连上真机后，再去启动WDA就能成功，经查看区别就是，真机链接时mount是否成功，当
try to mount developer disk image...download develop disk image fail
就会调起WDA失败，所以我想知道，新的WDA 包安装的情况下，mount会失败是什么原因，怎么解决呢，不能每次打开XCode链接使mount成功吧

**Comment by ZhouYixun** [comment]
> 这个意思是说，目前对于iOS16及以下系统，还不能用XCode15来构建是吧 另外还有个问题不知是否能解答，我用XCode14打WDA ipa包之后，发现首次安装到真机会出现Sib启动不了WDA的情况，log如下 2023-12-28 18:01:30.453 INFO 68097 --- [ Thread-10] com.msxf.mtp.agent.bridge.ios.SibTool : WebDriverAgent server start failed: receive packet: InvalidService 2023-12-28 18:01:30.453 INFO 68097 --- [ Thread-10] com.msxf.mtp.agent.bridge.ios.SibTool : WebDriverAgent print thread shutdown.
> 
> 但是真机一旦用XCode成功连上真机后，再去启动WDA就能成功，经查看区别就是，真机链接时mount是否成功，当 try to mount developer disk image...download develop disk image fail 就会调起WDA失败，所以我想知道，新的WDA 包安装的情况下，mount会失败是什么原因，怎么解决呢，不能每次打开XCode链接使mount成功吧

iOS版本多少

**Comment by guoxiangyang163** [comment]
iOS 16.1.1，我用的是XCode14.3，我以为是Xcode缺少[OSDeviceSupport/16.1.zip](https://github.com/JinjunHan/iOSDeviceSupport/blob/master/iOSDeviceSupport/16.1.zip)
的原因，当我把16.1镜像放进XCode相应 /Applications/Xcode_14.3.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport 目录后，进行打包，还是不行

**Comment by ZhouYixun** [comment]
> iOS 16.1.1，我用的是XCode14.3，我以为是Xcode缺少[OSDeviceSupport/16.1.zip](https://github.com/JinjunHan/iOSDeviceSupport/blob/master/iOSDeviceSupport/16.1.zip) 的原因，当我把16.1镜像放进XCode相应 /Applications/Xcode_14.3.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport 目录后，进行打包，还是不行

并不清楚你的流程，我这边ios16所有版本都没挂载失败的问题

**Comment by guoxiangyang163** [comment]
因为我的Xcode 14.3 /Applications/Xcode_14.3.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport 目录下只支镜像文件只到16.0，而有两部手机 iOS16.1.1，和iOS16.6，都出现过这个问题，现象是XCode14显示此手机并不被支持 unsupport，然而打开XCode15后就能迅速链接上真机，此时关闭XCode15，打开XCode14就也能成功链接真机了，然后mount就会成功，WDA也能被成功启动

**Comment by ZhouYixun** [comment]
挂载不依赖xcode，我win都可以
