### ISSUE TITLE
[Bug] sib  run wda时 Error while preparing for testing: (null)

### ISSUE THREAD

**Issue by qianhk** [SonicCloudOrg/sonic-ios-bridge#75]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

试了 1.3.17 ， 1.3.10， 1.3.6 在执行./sonic-ios-bridge run wda时都报错：
WebDriverAgentRunner-Runner[357:6521] [Default] Running tests...
WebDriverAgentRunner-Runner[357:6521] [Default] Error while preparing for testing: (null)

WebDriverAgentRunner 无论是sonic仓库的版本还是appium的版本都报这个错。
bundle id无论是官方的com.facebook.WebDriverAgentRunner.xctrunner还是自定义修改的都报错。

appium可以启动wda、tidevice xcuitest也可以启动。

### Deploy platform

macos 14.2.1 (23C71)

### Minimal reproduce step

手机iPhone SE 2 iOS 14.6版本
以及 iPhone15， iOS 17.2.1版本
都是这个现象。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
试下换低版本的xcode重新打包wda，这个问题我们还在看
