### ISSUE TITLE
[Bug] WebDriverAgent server start failed: receive packet: ServiceLimit%        

### ISSUE THREAD

**Issue by SuperChaoM** [SonicCloudOrg/sonic-ios-bridge#76]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sib version 
1.3.15

### Deploy platform

macos12.7.1

### Minimal reproduce step

adsl-172-10-3-213 ~ % sib -u 8e606e76913ab46d2ff4b4eddad8e2b0823f4e51 run wda
WebDriverAgent server start failed: receive packet: ServiceLimit%                                                           
adsl-172-10-3-213 ~ % sib -u 8e606e76913ab46d2ff4b4eddad8e2b0823f4e51 mount
mount successful!
adsl-172-10-3-213 ~ % sib -u 8e606e76913ab46d2ff4b4eddad8e2b0823f4e51 run wda
WebDriverAgent server start failed: receive packet: ServiceLimit%       一段时间后运行出现WebDriverAgent server start failed: receive packet: ServiceLimit

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by SuperChaoM** [comment]
目前使用xcode 调试xctest没有这个问题，sib需要重启手机后挂载才恢复正常；这是为什么？

**Comment by SuperChaoM** [comment]
是因为iPhone io读写文件太多超过了限制？ xcode不会？

**Comment by ZhouYixun** [comment]
https://sonic-cloud.cn/sib/re-sib.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

可以看下文档

**Comment by ZhouYixun** [comment]
而且你指令用错了，-u 应该接在 run wda后面，至于ServiceLimit问题是usbmuxd的报错信息，暂时无解
