### ISSUE TITLE
[Bug] WebDriverAgent server start failed: receive packet: InvalidService

### ISSUE THREAD

**Issue by fudy** [SonicCloudOrg/sonic-ios-bridge#78]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sib version
1.3.18

### Deploy platform

Macosx

### Minimal reproduce step

运行命令启动wda: 
    sib run wda -u <Iphone 10 UDID> -b 'com.fudy.wda'
报了如下错误：
WebDriverAgent server start failed: receive packet: InvalidService

相同的WDA.jar，试了一台Iphone 9的，是好的。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
ios版本是什么呢？

**Comment by fudy** [comment]
又试了几台
* 失败的：
iPhone 8        ios: 14.1
iPhone 8 Plus  ios: 15.1
iPhone XS     ios: 15.4.1
* 成功的：
iPhone 7        ios: 14.6

**Comment by fudy** [comment]
又试了几台
* 失败的：
iPhone 8        ios: 14.1
iPhone 8 Plus  ios: 15.1
iPhone XS     ios: 15.4.1
* 成功的：
iPhone 7        ios: 14.6

**Comment by ZhouYixun** [comment]
不是，你有挂载吗？

**Comment by ZhouYixun** [comment]
https://sonic-cloud.cn/sib/re-sib.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by fudy** [comment]
挂载也会失败的，不过好像重启手机后解决了，据说是调用了过多的runningProcess方法就会出现这种问题。

**Comment by fudy** [comment]
重启后恢复

**Comment by wangyuc** [comment]
发现 run wda 长时间运行会卡死，可以尝试现结束wda 进程，通过sib 的luanch 命令启动wda ，通过iproxy 转发端口，即可启动并访问wda。
目前该方法无法应用于ios17，测试ios15 16 可以使用。
