### ISSUE TITLE
可以提供获取地理位置的功能吗，现在只有模拟定位[Bug] 

### ISSUE THREAD

**Issue by Pycoder0901** [SonicCloudOrg/sonic-ios-bridge#79]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

最新

### Deploy platform

iOS

### Minimal reproduce step

新功能

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
似乎不行
