### ISSUE TITLE
[Bug] iPhone手机重启后，在使用sib启动WDA无法启动，WebDriverAgent server start failed: receive packet: InvalidService

### ISSUE THREAD

**Issue by yusandy0920** [SonicCloudOrg/sonic-ios-bridge#82]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.4

### Deploy platform

windows

### Minimal reproduce step

重启手机，使用sib启动wda

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
官网文档可以看一下，重启后需要挂载那一块

**Comment by yusandy0920** [comment]
重启后，使用tidevice启动wda可以解决

**Comment by ZhouYixun** [comment]
> 重启后，使用tidevice启动wda可以解决

找到原因了，最近的开发者镜像源关闭了，我更新下版本
