### ISSUE TITLE
[Bug] 安卓和iOS获取的sys_disk和sys_network性能数据和实际相差很大，是否能够优化

### ISSUE THREAD

**Issue by yusandy0920** [SonicCloudOrg/sonic-ios-bridge#83]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

{"type":"sys_disk","timestamp":1721382112,"data_read":517904439808,"data_written":283989688320,"reads_in":15095234,"writes_out":29326722}
{"type":"sys_network","timestamp":1721382112,"bytes_in":54485003939,"bytes_out":51020773787,"packets_in":22785517,"packets_out":12821389}

### Deploy platform

Windows 10, Macosx
sonic-ios-bridge version: 1.3.18

### Minimal reproduce step

获取iOS和安卓设备的disk和network性能数据

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
指标不太一样，这个是ios的原生数据
