### ISSUE TITLE
[Bug] mac mini上构建WDA.ipa后往iPhone12 Pro Max(17.4.1)上sib 安装失败

### ISSUE THREAD

**Issue by liuss01** [SonicCloudOrg/sonic-ios-bridge#86]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sonic-agent-v2.7.2-macosx_x86_64

### Deploy platform

mac mini os：Darwin 123deMac-mini.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:27 PDT 2024; root:xnu-11215.41.3~2/RELEASE_X86_64 x86_64
iPhone12 Pro Max：17.4.1

### Minimal reproduce step

1、构建好WDA.ipa后执行sib app install -p WDA.ipa报错
Error: failed send the command [install], you can use [sib mount] command to fix it and retry, err : lockdown start session: receive packet: InvalidHostID
Usage:
  /usr/local/bin/sib64 app install [flags]

Flags:
  -h, --help          help for install
  -p, --path string   path of ipa file
  -u, --udid string   device's serialNumber

Global Flags:
      --log-level string   Valid values: [panic, fatal, error, warn, info, debug, trace] (default "info")

2、执行sib mount失败
a@123deMac-mini Release-iphoneos % sib64 devices
00008101-001C20540C78001E online localhost

a@123deMac-mini Release-iphoneos % sib64 mount  
try to mount developer disk image...
a@123deMac-mini Release-iphoneos % 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
ios17以上只能走mac，用ideviceinstaller安装
