### ISSUE TITLE
[Bug] iOS17及以上版本的处理时报错 The requested device could not be found because no available devices matched the request.

### ISSUE THREAD

**Issue by liuss01** [SonicCloudOrg/sonic-ios-bridge#87]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sonic-agent-v2.7.2-macosx_x86_64

### Deploy platform

mac mini os：Darwin 123deMac-mini.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:27 PDT 2024; root:xnu-11215.41.3~2/RELEASE_X86_64 x86_64
iPhone12 Pro Max：17.4.1

### Minimal reproduce step

1、根据这里执行时报错
https://soniccloudorg.github.io/deploy/ios-deploy.html
2、在iOS17及以上版本的处理 步骤中
xcodebuild -project 你上面填的路径 -scheme WebDriverAgentRunner -destination 'id=设备的序列号' test
报错如下：
a@123deMac-mini sonic-agent-v2.7.2-macosx_x86_64 % xcodebuild -project /Users/a/Downloads/sonic-ios-wda/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id='F2LDP2E60D5K' test
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/a/Downloads/sonic-ios-wda/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=F2LDP2E60D5K test

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2024-11-08 21:40:52.613 xcodebuild[84491:1025608] Writing error result bundle to /var/folders/d3/0cwsy3190l561zq1vgs28xgm0000gn/T/ResultBundle_2024-08-11_21-40-0052.xcresult
xcodebuild: error: Unable to find a device matching the provided destination specifier:
		{ id:F2LDP2E60D5K }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "WebDriverAgentRunner" scheme:
		{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:C1982942-9BD3-5669-B8EE-170CD7A69376, name:My Mac }
		{ platform:iOS, arch:arm64, id:00008101-001C20540C78001E, name:123的iPhone }
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
		{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
		{ platform:iOS Simulator, id:92A94882-A47F-4EA2-96DC-54DBD0710259, OS:18.1, name:iPad (10th generation) }
		{ platform:iOS Simulator, id:4541F9B0-B7F6-45F7-967D-7089D1AF54C0, OS:18.1, name:iPad Air 11-inch (M2) }
		{ platform:iOS Simulator, id:D73C42BA-98C6-42E8-9F84-89D81C620C3F, OS:18.1, name:iPad Air 13-inch (M2) }
		{ platform:iOS Simulator, id:A28A3CAE-8683-42B1-81CA-AB218DFBE782, OS:18.1, name:iPad Pro 11-inch (M4) }
		{ platform:iOS Simulator, id:04255499-85EC-4720-A542-E960E0A29BE8, OS:18.1, name:iPad Pro 13-inch (M4) }
		{ platform:iOS Simulator, id:86E75860-08B8-4C60-B804-9717FFCBBD6B, OS:18.1, name:iPad mini (A17 Pro) }
		{ platform:iOS Simulator, id:D0BAEC36-4C0A-47D1-8167-05C14D0C9D39, OS:18.1, name:iPhone 16 }
		{ platform:iOS Simulator, id:67487AB3-5049-48E8-9895-7D4D37A2B4D0, OS:18.1, name:iPhone 16 Plus }
		{ platform:iOS Simulator, id:62E16839-7938-4D5D-B462-4C1DEDB19A37, OS:18.1, name:iPhone 16 Pro }
		{ platform:iOS Simulator, id:0571A6FF-39AD-4ACB-8FC0-D7BCB2AACD0B, OS:18.1, name:iPhone 16 Pro Max }
		{ platform:iOS Simulator, id:EDAECDFF-8170-409E-B761-853BEA50616D, OS:18.1, name:iPhone SE (3rd generation) }
a@123deMac-mini sonic-agent-v2.7.2-macosx_x86_64 % 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你需要升级xcode
